// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paschoalotto.Repositorio.Database.Context;

namespace Paschoalotto.Repositorio.Database.Migrations
{
    [DbContext(typeof(PaschoalottoContext))]
    partial class PaschoalottoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Paschoalotto.Dominio.Entidade.AcordoClientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Comissao")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataAcordo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Juros")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("PropostaId")
                        .HasColumnType("int");

                    b.Property<double>("TaxaJuros")
                        .HasColumnType("float");

                    b.Property<int>("TipoJuros")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("VencimentoParcelas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropostaId")
                        .IsUnique();

                    b.ToTable("AcordoCliente","provedordados");
                });

            modelBuilder.Entity("Paschoalotto.Dominio.Entidade.DividaClienteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.ToTable("DividaCliente","provedordados");
                });

            modelBuilder.Entity("Paschoalotto.Dominio.Entidade.PropostaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContatoColaborador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataProposta")
                        .HasColumnType("datetime2");

                    b.Property<int>("DividaId")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("JurosId")
                        .HasColumnType("int");

                    b.Property<double>("PorcentagemComissao")
                        .HasColumnType("float");

                    b.Property<int>("QtdMaximaParcelas")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DividaId")
                        .IsUnique();

                    b.HasIndex("JurosId")
                        .IsUnique();

                    b.ToTable("Propostas","provedordados");
                });

            modelBuilder.Entity("Paschoalotto.Dominio.Entidade.TipoJurosEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoJuros")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TipoJuros","provedordados");
                });

            modelBuilder.Entity("Paschoalotto.Dominio.Entidade.AcordoClientEntity", b =>
                {
                    b.HasOne("Paschoalotto.Dominio.Entidade.PropostaEntity", "Proposta")
                        .WithOne("Acordo")
                        .HasForeignKey("Paschoalotto.Dominio.Entidade.AcordoClientEntity", "PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Paschoalotto.Dominio.Entidade.PropostaEntity", b =>
                {
                    b.HasOne("Paschoalotto.Dominio.Entidade.DividaClienteEntity", "Divida")
                        .WithOne("Proposta")
                        .HasForeignKey("Paschoalotto.Dominio.Entidade.PropostaEntity", "DividaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paschoalotto.Dominio.Entidade.TipoJurosEntity", "Juros")
                        .WithOne("Proposta")
                        .HasForeignKey("Paschoalotto.Dominio.Entidade.PropostaEntity", "JurosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
